# Plugins
plugins:
- jekyll-sitemap
- jekyll-twitter-plugin
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', '/archive']


# Site Settings
title: "DevopsDays India 2022"
email: "organizers-2022@devopsdaysindia.org"
description: "DevopsDays India is a global event complementing other DevopsDays events across the world."
baseurl: "/"
url: "https://devopsdaysindia.org"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: "devopsdaysindia.org"
googleMapApiKey: "AIzaSyBgvlmcBMUJrQ4NXxwIWdvJgKdmAHMlfcQ"

# Organizer Info
organizerName: "emergingtechs"
organizerAlternateName: "DevopsDays India 2022"
organizerDescription: "DevopsDays India is a global event complementing other DevopsDays events across the world."
organizerEmail: "organizers-2022@devopsdaysindia.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "devopsdaysindia.org"

# Head
metaKeywords: "event, devops, containers, monitoring, CICD"
twitterAccount: "@DevOpsDaysIN"
socialImageSrcGooglePlus: "/img/seo/organizer-logo.png"
socialImageSrcTwitter: "/img/seo/organizer-logo.png"
socialImageSrcFacebook: "/img/seo/organizer-logo.png"

# Documents
c4pUrl: "https://docs.google.com/forms/d/e/1FAIpQLSccCh84Z_Ckt6Y5_2gERkN9cnGtVyGxhIxpx7cbuGjXH1swLg/viewform"
c4sponsorsUrl: "/assets/DevopsDaysIndia_Sponsorship_Prospectus.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/cod/", text: "Code Of Conduct"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "DevopsDays <typeout> 2022"
eventDate: "November 18-19, 2022"
typeoutTextValues: '"", "India"'
typeoutFallback: "India"
heroButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSccCh84Z_Ckt6Y5_2gERkN9cnGtVyGxhIxpx7cbuGjXH1swLg/viewform", text: "Become a speaker"}
 - {link: "https://devopsdaysindia.org/assets/DevopsDaysIndia_Sponsorship_Prospectus.pdf", text: "Become a sponsor"}
 - {link: "https://www.townscript.com/e/dodi-22", text: "Buy Tickets"}

# About Block
aboutBlock:
 - {title: "About DevopsDays India", image: "conference.png", text: "DevopsDays India is a technical event run by volunteers from 
 India as part of the worldwide DevOpsDays series covering topics such as software development, IT infrastructure 
 operations, and the intersection between them." }
# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "330", specialCharacter: "+", info: "attendees", detail: "from 75 companies"}
 - {count: "16", specialCharacter: "+", info: "hours", detail: "of pure Devops technologies"}
 - {count: "15", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "45", specialCharacter: "+", info: "attendees", detail: "female attendees"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "RADISSON BLU BENGALURU"
eventLocationLink: "https://goo.gl/maps/DWhhsQPq6cWrCkFW6"
eventStreetAddress: "SY NO 90, 4, SARJAPUR OUTER RING ROAD"
eventAddressLocality: "Marathahalli"
eventAddressLocalityRegion: "Bengaluru"
eventPostalCode: "560037"
eventAddressCountry: "India"
eventStartTime: "2019-09-13T09:00"
eventDoorTime: "08:30"
eventEndTime: "2019-09-14T18:00"
eventPlaceCoordinates: "12.950399, 77.89885"
mapCenterCoordinates: "12.950399, 77.89885"
mapMobileCenterCoordinates: "12.950399, 77.89885"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "DevopsDaysIN"
twitterFeed: "http://xxx/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Tickets Block
ticketsTitle: "Price Table"
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Regular Conference Ticket"
  price: "2542"
  priceCurrency: "INR"
  buyButtonLink: "https://www.townscript.com/e/dodi19/booking"
  buyButtonText: "Buy Now"
  additionalInfo: "Includes Swags, lunch and 2 times tea/coffee on both days; Drinks and Dinner on 13th"
  validFrom: "2019-08-01T10:00"
  validThrough: "2019-09-12T23:59"
 -
  name: "Workshop - Kubernetes 201"
  price: "3814"
  priceCurrency: "INR"
  featured: false
  buyButtonLink: "https://www.townscript.com/e/dodi19/booking"
  buyButtonText: "Buy Now"
  additionalInfo: "Workshop will be conducted on 12th Sept morning"
  validFrom: "2019-08-01T10:00"
  validThrough: "2019-09-11T23:59"
  disabled: false
 -
  name: "Workshop - Service Mesh"
  price: "3814"
  priceCurrency: "INR"
  buyButtonLink: "https://www.townscript.com/e/dodi19/booking"
  buyButtonText: "Buy Now"
  additionalInfo: "Workshop will be conducted on 12th Sept afternoon"
  validFrom: "2019-08-01T10:00"
  validThrough: "2019-09-11T23:59"
  soldOut: false
  soldOutText: "Sold Out"
 -
  name: "Workshops 1 & 2"
  price: "5932"
  priceCurrency: "INR"
  buyButtonLink: "https://www.townscript.com/e/dodi19/booking"
  buyButtonText: "Buy Now"
  additionalInfo: "Workshop will be conducted on 12th of Sept"
  validFrom: "2019-08-01T10:00"
  validThrough: "2019-09-11T23:59"
  soldOut: false
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/DevOpsDaysIN", icon: "twitter"}
 - {link: "https://www.facebook.com/devopsdaysin/", icon: "facebook"}
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:organizers-2022@devopsdaysindia.org", text: "organizers-2022@devopsdaysindia.org"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About Organizers"
aboutUs: "Devopsdays India is a global event complementing other Devopsdays events across the world."

#Toggles
showSpeakers: false
showSponsors: true
showSchedule: false
showLocation: false
showTickets: false
